name: Jest coverage report

on:
  workflow_dispatch:
  push:
  pull_request:
jobs:
  jest-coverage-report:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout projects"
        uses: actions/checkout@v2
      - name: "Install packages"
        run: yarn install
      - name: Jest coverage report
        uses: artiomtr/jest-coverage-report-action@v2.0-rc.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          package-manager: yarn
          test-script: yarn coverage
          #   threshold: 80 # optional parameter
